move output file of mk-httpd-ovf on failure so subsequent re-makes
On failure, mk-httpd-ovf would leave the .ovf file present.  This would
mean that the next invocation of 'make' would think that file was up
to date and not re-make it.  The change just moves it to '<output>.fail"
so it can be debugged there.

Signed-off-by: Scott Moser <ssmoser@linux.vnet.ibm.com>

diff --git a/examples/sample/mk-httpd-ovf b/examples/sample/mk-httpd-ovf
--- a/examples/sample/mk-httpd-ovf
+++ b/examples/sample/mk-httpd-ovf
@@ -13,20 +13,23 @@ domkovf() {
    out=$(${MKOVF} "$@" 2>&1) || {
       error "failed: ${MKOVF} $@"
       error "${out}"
+      mv "${OUT_FILE}" "${OUT_FILE}.fail" >/dev/null 2>&1 &&
+         error "failed output file in ${OUT_FILE}.fail"
       return 1
    }
 }
+
+outd=${1%/}
+f=${2:-${outd}/httpd.ovf}
+OUT_FILE=${f}
+[ -d "${outd}" ] || { echo "${outd} not a dir"; exit 1; }
+rm -f "${f}"
 
 if [ -z "${MKOVF}" ]; then
    { MKOVF=$(which mkovf.py) || MKOVF=$(which mkovf); } 2>/dev/null ||
       fail "cannot find mkovf. export MKOVF or add 'mkovf.py' to PATH"
 fi
 mkovf=domkovf
-
-outd=${1%/}
-f=${2:-${outd}/httpd.ovf}
-[ -d "${outd}" ] || { echo "${outd} not a dir"; exit 1; }
-rm -f "${f}"
 
 disks=$(ls ${outd}/*.qcow2 2>/dev/null) ||
    fail "failed to find disks in ${outd}/*.qcow2"
@@ -93,11 +96,6 @@ $mkovf --property -f "$f" --classDesc org.qemu \
 $mkovf --property -f "$f" --classDesc org.qemu \
    --key message  --type string --instance 1 \
    --description "Message string."
-
-
-
-
-
 
 $mkovf --virthw -f "$f" --id MyService --type qemu \
    --info "Virtual Hardware Requirements: 256Mb, 1 CPU, 1 disk, 1 nic" \
